# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT * FROM databricks_bootcamp_catalog.dlt_gold.dim_products WHERE product_id = 29

# COMMAND ----------

# MAGIC %sql
# MAGIC SELECT * FROM databricks_bootcamp_catalog.dlt_gold.products_silver WHERE product_id = 29

# COMMAND ----------

